### PR TITLE
Fix Rectangle select mode can disable switching rooms

### LINKED ISSUE #359: Rectangle select mode can disable switching rooms even after disabling rectangle select.
Bug originally found by IsaGoodFriend 

Bug:  Rectangle select mode can disable switching rooms even after disabling rectangle select.
Steps:  Enable rectangle select mode, and select anything.  Disable select mode.  You won't be able to change rooms at all

Probably caused by

`singleton->SetChangeCurrentRoomEnabled(false);` in MainGraphicsView.cpp line 68

Is this necessary to prevent a bug ? Or can we remove it safely ?

### PR DESCRIPTION
**Pull request by Kleyment**
Fix #359
Add ResetRect() and ResetRectPixmaps() in MainGraphicsView to avoid code duplication

### CODE REVIEW

File: EditorWindow/MainGraphicsView.cpp [hunk 1]
```diff
@@ -1,6 +1,7 @@
 ﻿#include "MainGraphicsView.h"
 #include "WL4EditorWindow.h"
 #include "Operation.h"
+#include "MainGraphicsView.h"
```
Comment (shinespeciall) [inline EditorWindow/MainGraphicsView.cpp:4]: duplicate with the first line in this file

**Review by shinespeciall — CHANGES_REQUESTED** [review]

**Review by shinespeciall — APPROVED** [review]
