### PR TITLE
Fix the crash problem for adding new rooms

### LINKED ISSUE #241: Corruption when adding new room
beco: seems like adding new room corrupts the rom if it's already edited before. i tried to add a room in my hack but it made the rom unopenable with the editor, also got the same result with your hack (HW).

### PR DESCRIPTION
**Pull request by shinespeciall**
Fixed #241

### CODE REVIEW

File: LevelComponents/Room.cpp [hunk 1]
```diff
@@ -1015,7 +1015,8 @@ namespace LevelComponents
     /// </summary>
     void Room::SetLayerDataPtr(int LayerNum, int dataPtr)
     {
-        assert(!(LayerNum & 0xFFFFFFFC) /* LayerNum must be within range [0, 4) */);
```
Comment (Goldensunboy) [inline LevelComponents/Room.cpp:1018]: Let's convert this into a debug warning and remove the comments

Comment (shinespeciall) [reply LevelComponents/Room.cpp:1018]: Done.
