### PR TITLE
Current file meta data impl and problems fix on OperationParams

### LINKED ISSUE #354: put ROMUtils::CurrentFile variables stuff into a struct so we don't need to change a lot of code when reading something from a temp file
example provided by @Goldensunboy 

struct ROMFileData
{
    unsigned int *Length;
    QString *FilePath;
    unsigned char **ROMAddr;
}

unsigned int CurrentFileLength;
unsigned int TmpFileLength;
QString CurrentFilePath;
QString TmpFilePath;
unsigned char *CurrentFile;
unsigned char *TmpFile;

struct ROMFileData CurrentFile =
{
    &CurrentFileLength,
    &CurrentFilePath,
    &CurrentFile
};

struct ROMFileData TmpFile =
{
    &TmpFileLength,
    &TmpFilePath,
    &TmpFile
};

struct ROMFileData *CurrentFileData = &CurrentFile;

...

int main()
{
    int len = *CurrentFileData->CurrentFileLength;
    CurrentFileData = &TmpFile;
    int tmpLen = *CurrentFileData->CurrentFileLength;
}

### LINKED ISSUE #364: a potential memory leak problem crashes the editor
repro steps:
open a vanilla rom;
switch to the first level in emerald passage;
import a bonus Tileset (Id: 0x58) into the current rom;
go to Room 10 of the current level (which is a bonus Room);
open Room Config Dialog and let it use Tileset 0x58 instead of 0x59, hit OK to apply the changes;
now hit "Load Level" button and hit "Save" when the pop up shows;
then hit "Load Level" button again and load the current level (i.e. the first level in emerald passage), now the current Room is Room 0;
now use ">" button to go to Room 10, if the editor does not crash, then open the Tileset Editor, it will crash anyway.

### PR DESCRIPTION
**Pull request by shinespeciall**
Resolve #354 
Fix #364

### CODE REVIEW

File: ROMUtils.cpp [hunk 1]
```diff
@@ -41,6 +41,10 @@ namespace ROMUtils
     unsigned char *tmpCurrentFile;
     unsigned int tmpCurrentFileSize;
     QString tmpROMFilePath;
+    struct ROMFileMetaData CurrentROMMetaData;
+    struct ROMFileMetaData TemROMMetaData;
```
Comment (Goldensunboy) [inline ROMUtils.cpp:45]: TempROMMetadata (missing the p) also let's name these as "Metadata" instead of MetaData (metadata is one word)

**Review by Goldensunboy — CHANGES_REQUESTED** [review]

**Review by Goldensunboy — APPROVED** [review]
